// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConnectionMonitorController from "./connection_monitor_controller"
application.register("connection-monitor", ConnectionMonitorController)

import SwapController from "./swap_controller"
application.register("swap", SwapController)

import Dialog from '@stimulus-components/dialog'
application.register('dialog', Dialog)

import RevealController from '@stimulus-components/reveal'
application.register('reveal', RevealController)
