---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
linters:
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: true
  PartialInstanceVariable:
    enabled: true
  RequireScriptNonce:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/HashAlignment:
        Enabled: false
      Layout/ArgumentAlignment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
  StrictLocals:
    enabled: true
