version: 0.9.5

linter:
  enabled: true

  rules:
    erb-strict-locals-comment-syntax:
      enabled: false
    actionview-strict-locals-partial-only:
      enabled: false

formatter:
  enabled: false
