plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'test/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes
