---
shared:
  - AFRICA
  - AGENT
  - AIR
  - ALIEN
  - ALPS
  - AMAZON
  - AMBULANCE
  - AMERICA
  - ANCHOR
  - ANGEL
  - ANT
  - ANTARCTICA
  - APPLE
  - ARM
  - ATLANTIS
  - AUSTRALIA
  - AVALANCHE
  - AXE
  - AZTEC
  - BACK
  - BACON
  - BALL
  - BALLOON
  - BANANA
  - BAND
  - BANK
  - BAR
  - BARBECUE
  - BARK
  - BAT
  - BATTERY
  - BAY
  - BEACH
  - BEAN
  - BEAR
  - BEARD
  - BEAT
  - BED
  - BEIJING
  - BELL
  - BELT
  - BENCH
  - BERLIN
  - BERMUDA
  - BERRY
  - BIKINI
  - BILL
  - BISCUIT
  - BLIND
  - BLIZZARD
  - BLOCK
  - BOARD
  - BOLT
  - BOMB
  - BOND
  - BONSAI
  - BOOK
  - BOOM
  - BOOT
  - BOSS
  - BOTTLE
  - BOW
  - BOWLER
  - BOX
  - BRASS
  - BRAZIL
  - BREAD
  - BREAK
  - BRICK
  - BRIDGE
  - BROTHER
  - BRUSH
  - BUBBLE
  - BUCK
  - BUCKET
  - BUFFALO
  - BUG
  - BUGLE
  - BULB
  - BUNK
  - BUTTER
  - BUTTERFLY
  - BUTTON
  - CABLE
  - CAESAR
  - CAKE
  - CALF
  - CANADA
  - CANE
  - CAP
  - CAPITAL
  - CAPTAIN
  - CAR
  - CARD
  - CARIBBEAN
  - CARROT
  - CASINO
  - CAST
  - CASTLE
  - CAT
  - CAVE
  - CELL
  - CENTAUR
  - CENTER
  - CHAIN
  - CHAIR
  - CHALK
  - CHANGE
  - CHARGE
  - CHECK
  - CHEESE
  - CHERRY
  - CHEST
  - CHICK
  - CHINA
  - CHOCOLATE
  - CHRISTMAS
  - CHURCH
  - CIRCLE
  - CLEOPATRA
  - CLIFF
  - CLOAK
  - CLOUD
  - CLUB
  - CODE
  - COLD
  - COMIC
  - COMPOUND
  - CONCERT
  - CONDUCTOR
  - CONE
  - CONTRACT
  - COOK
  - COPPER
  - COTTON
  - COUNTRY
  - COURT
  - COVER
  - COWBOY
  - CRAB
  - CRAFT
  - CRANE
  - CRASH
  - CRICKET
  - CROSS
  - CROWN
  - CRUISE
  - CRYSTAL
  - CURRY
  - CYCLE
  - CZECH
  - DANCE
  - DASH
  - DATE
  - DAY
  - DEATH
  - DECK
  - DEGREE
  - DELTA
  - DENTIST
  - DIAMOND
  - DICE
  - DINOSAUR
  - DIRECTOR
  - DISEASE
  - DISK
  - DOCTOR
  - DOG
  - DRAFT
  - DRAGON
  - DRAWING
  - DRESS
  - DRESSING
  - DRILL
  - DRIVER
  - DRONE
  - DROP
  - DRYER
  - DUCK
  - DUST
  - DWARF
  - EAGLE
  - EAR
  - EARTH
  - EGG
  - EGYPT
  - EINSTEIN
  - ELEPHANT
  - EMBASSY
  - ENGINE
  - ENGLAND
  - EUROPE
  - EYE
  - FACE
  - FAIR
  - FALL
  - FAN
  - FENCE
  - FEVER
  - FIDDLE
  - FIELD
  - FIGHTER
  - FIGURE
  - FILE
  - FILM
  - FIRE
  - FISH
  - FLAG
  - FLOOD
  - FLOOR
  - FLUTE
  - FLY
  - FOG
  - FOOT
  - FORCE
  - FOREST
  - FORK
  - FRANCE
  - FROG
  - FROST
  - GAME
  - GANGSTER
  - GAS
  - GEAR
  - GENIE
  - GENIUS
  - GERMANY
  - GHOST
  - GIANT
  - GLACIER
  - GLASS
  - GLOVE
  - GOLD
  - GOLDILOCKS
  - GOVERNOR
  - GRACE
  - GRASS
  - GREECE
  - GREEN
  - GREENHOUSE
  - GROUND
  - GYMNAST
  - HALLOWEEN
  - HAM
  - HAMMER
  - HAND
  - HAWK
  - HEAD
  - HEART
  - HELICOPTER
  - HELMET
  - HIDE
  - HIMALAYAS
  - HOLE
  - HOLLYWOOD
  - HONEY
  - HOOD
  - HOOK
  - HORN
  - HORSE
  - HORSESHOE
  - HOSE
  - HOSPITAL
  - HOTEL
  - ICE
  - ICE CREAM
  - IGLOO
  - INDIA
  - IRON
  - IVORY
  - JACK
  - JAIL
  - JAM
  - JAPAN
  - JET
  - JUPITER
  - KANGAROO
  - KERNEL
  - KETCHUP
  - KEY
  - KICK
  - KID
  - KILT
  - KING
  - KISS
  - KITCHEN
  - KIWI
  - KNIFE
  - KNIGHT
  - KNOT
  - LAB
  - LADDER
  - LAP
  - LASER
  - LAWYER
  - LEAD
  - LEATHER
  - LEMON
  - LEMONADE
  - LEPRECHAUN
  - LETTER
  - LIFE
  - LIGHT
  - LIMOUSINE
  - LINE
  - LINK
  - LION
  - LIP
  - LITTER
  - LOCH NESS
  - LOCK
  - LOG
  - LONDON
  - LUCK
  - MACARONI
  - MAGAZINE
  - MAGICIAN
  - MAIL
  - MAMMOTH
  - MANICURE
  - MAPLE
  - MARATHON
  - MARBLE
  - MARCH
  - MARK
  - MASS
  - MATCH
  - MERCURY
  - MESS
  - MEXICO
  - MICROSCOPE
  - MILK
  - MILL
  - MILLIONAIRE
  - MINE
  - MINT
  - MISS
  - MISSILE
  - MOD
  - MODEL
  - MOHAWK
  - MOLE
  - MONKEY
  - MOON
  - MOSCOW
  - MOSES
  - MOTHER
  - MOUNT
  - MOUNTIE
  - MOUSE
  - MOUTH
  - MUG
  - NAIL
  - NAPOLEON
  - NEEDLE
  - NET
  - NEWTON
  - NEW YORK
  - NIGHT
  - NINJA
  - NOTE
  - NOTRE DAME
  - NOVEL
  - NURSE
  - NUT
  - OASIS
  - OCTOPUS
  - OIL
  - OLIVE
  - OLYMPUS
  - ONION
  - OPERA
  - ORANGE
  - ORGAN
  - PAD
  - PAINT
  - PALM
  - PAN
  - PANTS
  - PAPER
  - PARACHUTE
  - PARK
  - PART
  - PASS
  - PASTE
  - PATIENT
  - PENGUIN
  - PENNY
  - PEPPER
  - PEW
  - PHOENIX
  - PIANO
  - PIE
  - PIG
  - PILLOW
  - PILOT
  - PIN
  - PINE
  - PIPE
  - PIRATE
  - PISTOL
  - PIT
  - PITCH
  - PITCHER
  - PIZZA
  - PLANE
  - PLASTIC
  - PLATE
  - PLATYPUS
  - PLAY
  - PLOT
  - POINT
  - POISON
  - POLE
  - POLICE
  - POLISH
  - POOL
  - POPCORN
  - PORT
  - POST
  - POUND
  - POWDER
  - PRESS
  - PRINCESS
  - PUMPKIN
  - PUPIL
  - PUPPET
  - PURSE
  - PYRAMID
  - QUACK
  - QUEEN
  - RABBIT
  - RACKET
  - RADIO
  - RAIL
  - RAINBOW
  - RAM
  - RAT
  - RAY
  - RAZOR
  - RECORD
  - REINDEER
  - REVOLUTION
  - RING
  - RIP
  - ROAD
  - ROBIN
  - ROBOT
  - ROCK
  - ROLL
  - ROME
  - ROOF
  - ROOT
  - ROPE
  - ROSE
  - ROULETTE
  - ROUND
  - ROW
  - RUBBER
  - RULER
  - RUST
  - SACK
  - SADDLE
  - SAHARA
  - SALAD
  - SALT
  - SANTA
  - SATELLITE
  - SATURN
  - SAUSAGE
  - SAW
  - SCALE
  - SCARECROW
  - SCHOOL
  - SCIENTIST
  - SCORPION
  - SCRATCH
  - SCREEN
  - SCROLL
  - SCUBA DIVER
  - SEAL
  - SECOND
  - SERVER
  - SHADOW
  - SHAKESPEARE
  - SHAMPOO
  - SHARK
  - SHED
  - SHEET
  - SHERLOCK
  - SHIP
  - SHOE
  - SHOP
  - SHORTS
  - SHOT
  - SHOULDER
  - SINK
  - SISTER
  - SKATES
  - SKULL
  - SKYSCRAPER
  - SLING
  - SLIP
  - SLIPPER
  - SLOTH
  - SLUG
  - SMOKE
  - SMUGGLER
  - SNAKE
  - SNAP
  - SNOW
  - SNOWMAN
  - SOCK
  - SOLDIER
  - SOUL
  - SOUND
  - SPACE
  - SPELL
  - SPIDER
  - SPIKE
  - SPINE
  - SPIRIT
  - SPOON
  - SPOT
  - SPRAY
  - SPRING
  - SPURS
  - SPY
  - SQUARE
  - SQUASH
  - SQUIRREL
  - STABLE
  - STADIUM
  - STAFF
  - STAR
  - STATE
  - STEAM
  - STEEL
  - STICK
  - STICKER
  - STOCK
  - STORM
  - STORY
  - STRAW
  - STREAM
  - STREET
  - STRIKE
  - STRING
  - SUB
  - SUGAR
  - SUIT
  - SUMO
  - SUN
  - SUPERHERO
  - SWAMP
  - SWEAT
  - SWING
  - SWITCH
  - TABLE
  - TABLET
  - TAG
  - TAIL
  - TANK
  - TAP
  - TEA
  - TEACHER
  - TEAM
  - TEAR
  - TELESCOPE
  - TEMPLE
  - TERMINAL
  - TEXAS
  - THEATER
  - THIEF
  - THUMB
  - TICK
  - TIE
  - TIME
  - TOAST
  - TOKYO
  - TOOTH
  - TORCH
  - TOWER
  - TRACK
  - TRAIN
  - TRIANGLE
  - TRIP
  - TROLL
  - TRUNK
  - TUBE
  - TURBO
  - TURKEY
  - TURTLE
  - TUXEDO
  - UNDERTAKER
  - UNICORN
  - VACUUM
  - VALENTINE
  - VAN
  - VENUS
  - VET
  - WAKE
  - WALL
  - WALRUS
  - WAR
  - WASHER
  - WASHINGTON
  - WATCH
  - WATER
  - WAVE
  - WEB
  - WELL
  - WEREWOLF
  - WHALE
  - WHEEL
  - WHEELCHAIR
  - WHIP
  - WHISTLE
  - WIND
  - WINDOW
  - WING
  - WISH
  - WITCH
  - WIZARD
  - WONDERLAND
  - WOOD
  - WORM
  - YARD
  - ZOMBIE
