module ApplicationCable
  class Channel < ::ActionCable::Channel::Base
    attr_reader current_user: ::User
  end

  class Connection < ::ActionCable::Connection::Base
    attr_accessor current_user: ::User

    def connect: () -> void

    private

    def find_verified_user: () -> ::User
  end
end

interface _GameAdapter
  def on_player_connected: (String player_id) -> void
  def on_player_disconnected: (String player_id) -> void
end

class PlayerChannel < ::ApplicationCable::Channel
  extend Turbo::Streams::StreamName
  include Turbo::Streams::StreamName::ClassMethods

  def subscribed: () -> void
  def unsubscribed: () -> void

  private

  attr_reader player: ::Player

  def adapter: () -> _GameAdapter
end
