module ApplicationCable
  class Channel < ::ActionCable::Channel::Base
    attr_reader current_user: ::User
  end

  class Connection < ::ActionCable::Connection::Base
    attr_accessor current_user: ::User

    def connect: () -> void

    private

    def find_verified_user: () -> ::User
  end
end

class PlayerChannel < ::ApplicationCable::Channel
  include Turbo::Streams::StreamName::ClassMethods

  def subscribed: () -> void
  def unsubscribed: () -> void

  private

  attr_reader game_kind: Symbol
  attr_reader player: ::Player
end
