interface _Online
  def online?: () -> bool
end

interface _ToGidParam
  def to_gid_param: () -> String
end

interface _ToModel
  def to_model: () -> ActiveRecord::Base
end

interface _ToParam
  def to_param: () -> String
end

class NormalizedString
  def initialize: (_ToS string) -> void

  def <=>: (NormalizedString other) -> Integer
  def ==: (NormalizedString other) -> bool
  def as_json: () -> String
  def blank?: () -> bool
  def eql?: (NormalizedString other) -> bool
  def hash: () -> Integer
  def length: () -> Integer
  def sortable_value: () -> String
  def to_s: () -> String

  private

  attr_reader string: String

  def normalize: (_ToS value) -> String
end

class PlayerConnections
  include Singleton

  def self.instance: () -> PlayerConnections

  def initialize: () -> void

  def count: (Integer player_id) -> Integer
  def increment: (Integer player_id) -> Integer
  def decrement: (Integer player_id) -> Integer

  private

  attr_reader connection_map: Concurrent::Map[Integer, Integer]
end

class Errors
  class Error
    attr_reader attribute: Symbol
    attr_reader message: String

    def initialize: (attribute: (Symbol | String), message: _ToS) -> void
    def full_message: () -> String
    def to_s: () -> String
    def ==: (untyped other) -> bool
    def eql?: (untyped other) -> bool
    def hash: () -> Integer
  end

  def initialize: () -> void
  def add: (Symbol | String, message: _ToS) -> void
  def added?: (Symbol | String, message: _ToS) -> bool
  def empty?: () -> bool
  def []: (Symbol | String) -> Array[Error]

  private

  attr_reader errors: Hash[Symbol, Set[Error]]
end
