module LoadedQuestions
  class AnswerForm
    attr_reader answer: ::NormalizedString
    attr_reader errors: ::Errors

    def initialize: (?answer: _ToS?) -> void

    def show?: () -> bool
    def valid?: () -> bool

    private

    def validate_length: (::NormalizedString value, min: Integer, max: Integer) -> String?
  end

  class Game
    type json_guessed_answer = { player_id: String, guessed_player_id: String }
    type json_document = {
      question: String,
      guesses: Array[json_guessed_answer],
      status: String
    }
    type document = {
      question: NormalizedString,
      guesses: Guesses,
      status: Status
    }

    MIN_QUESTION_LENGTH: Integer
    MAX_QUESTION_LENGTH: Integer

    def self.find: (String id) -> Game
    private def self.scope: () -> ::Game::ActiveRecord_Relation

    @players: Array[Player]

    attr_reader guesses: Guesses
    attr_reader question: NormalizedString
    attr_reader status: Status

    def initialize: (::Game game) -> void

    def id: () -> String
    def guesser: () -> Player
    def guesses=: (Guesses new_guesses) -> void
    def find_player: (Integer id) -> Player
    def player_for!: (String user_id) -> Player
    def player_for: (String user_id) -> Player?
    def players: () -> Array[Player]
    def question=: (NormalizedString new_question) -> void
    def save!: () -> void
    def status=: (Status new_status) -> void
    def swap_guesses: (player_id1: Integer, player_id2: Integer) -> void
    def to_model: () -> ::Game
    def update_status: (Status status) -> void

    private

    attr_reader model: ::Game

    def document: () -> document
    def json_document: () -> json_document
    def validate_between!: (::NormalizedString value, min: Integer, max: Integer, field: Symbol) -> void

    class Guesses
      def self.parse: (
        Array[json_guessed_answer] guesses,
        players: Array[Player]
      ) -> Guesses

      include Enumerable[GuessedAnswer]

      def initialize: (guesses: Array[GuessedAnswer]) -> void

      def each: () { (GuessedAnswer) -> void } -> self
      def find: (Integer player_id) -> GuessedAnswer
      def size: () -> Integer
      def swap: (player_id1: Integer, player_id2: Integer) -> self
      def as_json: () -> Array[json_guessed_answer]
      def score: () -> Integer

      private

      # @dynamic guesses
      attr_reader guesses: Array[GuessedAnswer]

      class GuessedAnswer
        attr_reader player: Player
        attr_reader guessed_player: Player

        def initialize: (player: Player, guessed_player: Player) -> void
        def answer: () -> ::NormalizedString
        def guessed_answer: () -> ::NormalizedString
        def correct?: () -> bool
        def as_json: () -> json_guessed_answer
      end
    end

    class Status
      def self.completed: () -> Status
      def self.guessing: () -> Status
      def self.parse: (String status) -> Status
      def self.polling: () -> Status

      attr_reader status: Symbol

      def initialize: (Symbol status) -> void

      def ==: (Status other) -> bool
      def as_json: () -> String
      def completed?: () -> bool
      def eql?: (Status other) -> bool
      def hash: () -> Integer
      def guessing?: () -> bool
      def polling?: () -> bool
      def to_s: () -> String
    end
  end

  module Broadcast
    class PlayerCreated
      def initialize: (player_id: String) -> void
      def call: () -> void

      private

      attr_reader created_player: ::Player
    end

    class PlayerConnected
      def initialize: (player_id: String) -> void
      def call: () -> void

      private

      attr_reader connected_player: ::Player
    end

    class PlayerDisconnected
      def initialize: (player_id: String) -> void
      def call: () -> void

      private

      attr_reader disconnected_player: ::Player
    end

    class AnswerUpdated
      def initialize: (player_id: String) -> void
      def call: () -> void

      private

      attr_reader updated_player: ::Player
    end

    class GuessingRoundStarted
      def initialize: (game_id: String) -> void
      def call: () -> void

      private

      attr_reader game_id: String
    end

    class AnswersSwapped
      def initialize: (game_id: String) -> void
      def call: () -> void

      private

      attr_reader game_id: String
    end

    class RoundCompleted
      def initialize: (game_id: String) -> void
      def call: () -> void

      private

      attr_reader game_id: String
    end

    class RoundCreated
      def initialize: (game_id: String) -> void
      def call: () -> void

      private

      attr_reader game_id: String
    end

    class PlayerNameUpdated
      def initialize: (player_id: String) -> void
      def call: () -> void

      private

      attr_reader updated_player: ::Player
    end
  end

  class GamesController < ::ApplicationController
    def new: () -> untyped
    def create: () -> untyped
    def show: () -> untyped
    def new_round: () -> untyped
    def create_round: () -> untyped
    def completed_round: () -> untyped
    def guessing_round: () -> untyped
    def swap_guesses: () -> untyped

    private

    def new_game_params: () -> ::ActionController::Parameters
    def new_round_params: () -> ::ActionController::Parameters
    def swap_params: () -> ::ActionController::Parameters
  end

  class CompletedRoundForm
    attr_reader errors: ::Errors

    def initialize: (game: Game) -> void

    def valid?: () -> bool

    private

    attr_reader game: Game
  end

  class GuessingRoundForm
    MIN_ANSWERED: Integer

    attr_reader errors: ::Errors

    def initialize: (game: Game) -> void

    def valid?: () -> bool

    private

    attr_reader game: Game
  end

  class CreateNewGame
    def initialize: (
      user: ::User,
      player_name: ::NormalizedString,
      question: ::NormalizedString
    ) -> void

    def call: () -> ::Game

    private

    attr_reader user: ::User
    attr_reader player_name: ::NormalizedString
    attr_reader question: ::NormalizedString

    def document: () -> Game::document
  end

  class CreateNewRound
    def initialize: (
      game: Game,
      guesser: Player,
      question: ::NormalizedString
    ) -> void

    def call: () -> Game

    private

    attr_reader game: Game
    attr_reader guesser: Player
    attr_reader question: ::NormalizedString

    def game_document: () -> Game::document
    def player_document: (Player player) -> Player::document
  end

  class NewGameForm
    attr_reader errors: ::Errors
    attr_reader player_name: ::NormalizedString
    attr_reader question: ::NormalizedString

    def initialize: (
      ?player_name: _ToS?,
      ?question: _ToS?
    ) -> void

    def valid?: () -> bool

    private

    def validate_length: (::NormalizedString value, min: Integer, max: Integer) -> String?
  end

  class NewRoundForm
    attr_reader errors: ::Errors
    attr_reader question: ::NormalizedString

    def initialize: (game: Game, ?question: _ToS?) -> void

    def valid?: () -> bool

    private

    attr_reader game: Game

    def validate_length: (::NormalizedString value, min: Integer, max: Integer) -> String?
  end

  class CreateNewPlayer
    def initialize: (game_id: String, user: ::User, name: ::NormalizedString, ?guesser: bool) -> void

    def call: () -> ::Player

    private

    attr_reader game_id: String
    attr_reader guesser: bool
    attr_reader name: ::NormalizedString
    attr_reader user: ::User

    def document: () -> Player::document
  end

  class NewPlayerForm
    attr_reader errors: ::Errors
    attr_reader game: Game
    attr_reader name: ::NormalizedString
    attr_reader user: ::User

    def initialize: (game: Game, user: ::User, ?name: _ToS?) -> void

    def valid?: () -> bool

    private

    def validate_length: (::NormalizedString value, min: Integer, max: Integer) -> String?
  end

  class EditPlayerForm
    attr_reader errors: ::Errors
    attr_reader game: Game
    attr_reader current_player: Player
    attr_reader name: ::NormalizedString

    def initialize: (game: Game, current_player: Player, ?name: _ToS?) -> void

    def valid?: () -> bool

    private

    def validate_length: (::NormalizedString value, min: Integer, max: Integer) -> String?
  end

  class Player
    MIN_ANSWER_LENGTH: Integer
    MAX_ANSWER_LENGTH: Integer

    type json_document = {
      answer: String,
      guesser: bool,
      score: Integer
    }
    type document = {
      answer: ::NormalizedString,
      guesser: bool,
      score: Integer
    }

    def self.build: (game_id: String, user_id: String) -> Player

    @guesser: bool

    attr_reader answer: ::NormalizedString
    attr_reader name: ::NormalizedString
    attr_reader score: Integer

    def initialize: (::Player model) -> void

    def <=>: (Player other) -> Integer
    def ==: (Player other) -> bool
    def answer=: (::NormalizedString new_answer) -> void
    def answered?: () -> bool
    def eql?: (Player other) -> bool
    def game_id: () -> String
    def guesser?: () -> bool
    def guesser=: (bool is_guesser) -> void
    def hash: () -> Integer
    def id: () -> String
    def name=: (::NormalizedString new_name) -> void
    def online?: () -> bool
    def save!: () -> void
    def score=: (Integer new_score) -> void
    def to_model: () -> ::Player
    def user_id: () -> String

    private

    attr_reader model: ::Player

    def document: () -> document
    def json_document: () -> json_document
    def validate_between!: (::NormalizedString value, min: Integer, max: Integer, field: Symbol) -> void
  end

  class PlayersController < ::ApplicationController
    def new: () -> untyped
    def create: () -> untyped
    def edit: () -> untyped
    def update: () -> untyped
    def answer: () -> untyped

    private

    def answer_params: () -> ::ActionController::Parameters
    def new_player_params: () -> ::ActionController::Parameters
    def update_player_params: () -> ::ActionController::Parameters
    def redirect_to_game: (Game game) -> void
    def redirect_to_new_player: (Game game) -> void
  end

  class Questions
    include Singleton

    def self.instance: () -> Questions

    def initialize: () -> void

    def question: () -> String

    private

    attr_reader questions: Array[String]

    def load_questions: () -> Array[String]
  end
end
