class ApplicationRecord < ::ActiveRecord::Base
end

class Game < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Game, ::Game::ActiveRecord_Relation, Integer]

  MIN_QUESTION_LENGTH: Integer
  MAX_QUESTION_LENGTH: Integer

  def self.loaded_questions: () -> ::Game::ActiveRecord_Relation

  def broadcast_reload_game: () -> void
  def broadcast_reload_players: () -> void
  def document: () -> String
  def document=: (String) -> String
  def kind: () -> Symbol
  def kind=: (Symbol) -> Symbol
  def parsed_document: () -> Hash[Symbol, untyped]
  def players: () -> ::Player::ActiveRecord_Associations_CollectionProxy
  def players=: (::Player::ActiveRecord_Associations_CollectionProxy | Array[::Player]) -> (::Player::ActiveRecord_Associations_CollectionProxy | Array[::Player])
  def player_ids: () -> Array[Integer]
  def player_ids=: (Array[Integer]) -> Array[Integer]
  def slug: () -> String
  def slug=: (String) -> String

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    def loaded_questions: () -> ::Game::ActiveRecord_Relation

    include ::_ActiveRecord_Relation[::Game, Integer]
    include ::Enumerable[::Game]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::ActiveRecord::Relation::Methods[::Game, Integer]
  end
end

class Player < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Player, ::Player::ActiveRecord_Relation, Integer]

  MIN_NAME_LENGTH: Integer
  MAX_NAME_LENGTH: Integer

  def document: () -> String
  def document=: (String) -> String
  def document?: () -> bool
  def game: () -> ::Game
  def game=: (::Game?) -> ::Game?
  def game_id: () -> Integer?
  def game_id=: (::Integer?) -> ::Integer?
  def online?: () -> bool
  def name: () -> ::NormalizedString
  def name=: (::NormalizedString) -> ::NormalizedString
  def name?: () -> bool
  def parsed_document: () -> Hash[Symbol, untyped]
  def to_gid_param: () -> String
  def user: () -> ::User
  def user=: (::User?) -> ::User?

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::_ActiveRecord_Relation[::Player, Integer]
    include ::Enumerable[::Player]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::ActiveRecord::Relation::Methods[::Player, Integer]
  end
end

class User < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::User, ::User::ActiveRecord_Relation, Integer]

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::_ActiveRecord_Relation[::User, Integer]
    include ::Enumerable[::User]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::ActiveRecord::Relation::Methods[::User, Integer]
  end
end
